services:

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - auth-service
      - question-service
      - notification-service

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 10

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  # -------------------------------------
  # AUTH SERVICE
  # -------------------------------------
  auth-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  auth-service:
    build:
      context: ./auth-service
    ports:
      - "8000:8000"
    depends_on:
      auth-db:
        condition: service_healthy
    environment:
      - DB_HOST=auth-db
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

  # -------------------------------------
  # QUESTION SERVICE
  # -------------------------------------
  question-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: question_db
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  question-service:
    build:
      context: ./question-service
    ports:
      - "8001:8000"
    depends_on:
      question-db:
        condition: service_healthy
      redis:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    environment:
      - DB_HOST=question-db
      - REDIS_HOST=redis
      - RABBITMQ_HOST=rabbitmq
      - ELASTICSEARCH_HOST=elasticsearch
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

  # -------------------------------------
  # NOTIFICATION SERVICE
  # -------------------------------------
  notification-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: notification_db
    ports:
      - "5435:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  notification-service:
    build:
      context: ./notification-service
    ports:
      - "8003:8000"
    depends_on:
      notification-db:
        condition: service_healthy
      rabbitmq:
        condition: service_started
      redis:
        condition: service_started
    environment:
      - DB_HOST=notification-db
      - RABBITMQ_HOST=rabbitmq
      - REDIS_HOST=redis
    command: >
      sh -c "python manage.py migrate &&
             daphne -b 0.0.0.0 -p 8000 config.asgi:application"

  notification-listener:
    build:
      context: ./notification-service
    command: python manage.py listen_rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy
      notification-db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - DB_HOST=notification-db
      - RABBITMQ_HOST=rabbitmq
      - REDIS_HOST=redis

  question-celery-worker:
    build:
      context: ./question-service
    command: celery -A config worker -l info
    depends_on:
      rabbitmq:
        condition: service_healthy
      question-db:
        condition: service_healthy
    environment:
      - DB_HOST=question-db
      - REDIS_HOST=redis
      - RABBITMQ_HOST=rabbitmq

