services:

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - auth-service
      - question-service

  # -------------------------------------
  # AUTH SERVICE
  # -------------------------------------
  auth-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"

  auth-service:
    build: 
      context: ./auth-service
    ports:
      - "8000:8000"
    depends_on:
      - auth-db
    environment:
      - DB_HOST=auth-db
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

  # -------------------------------------
  # QUESTION SERVICE
  # -------------------------------------
  question-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: question_db
    ports:
      - "5433:5432"

  question-service:
    build: 
      context: ./question-service
    ports:
      - "8001:8000"
    depends_on:
      - question-db
    environment:
      - DB_HOST=question-db
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

  # -------------------------------------
  # NOTIFICATION SERVICE
  # -------------------------------------
  notification-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: notification_db
    ports:
      - "5435:5432"

  notification-service:
    build: 
      context: ./notification-service
    ports:
      - "8003:8000"
    depends_on:
      - notification-db
    environment:
      - DB_HOST=notification-db
    command: >
      sh -c "python manage.py migrate &&
             daphne -b 0.0.0.0 -p 8000 config.asgi:application"

  # TODO: Redis, RabbitMQ, and Elasticsearch containers - to be implemented by hand
